### ISSUE TITLE
Erreur d'exécution

### ISSUE THREAD

**Issue by smoysan** [soapower/soapower#29]
Bonjour,

La version 1.0.6 ne se lance pas correctement. Pas de problème sur les versions 1.0.4 et 1.0.5. Ma configuration est identique pour toute version (pas d'utilisation de application-prod.conf pour mysql entre autre).

La stack 
[root@xxx current]# ./restart.sh
Restart Soapower
Soapower Home: /opt/soapower, port : 9010
Soapower Current: /opt/soapower/current
Stopping Soapower
Starting Soapower
Play server process ID is 3372
Oops, cannot start the server.
Configuration error: Configuration error[application: application.conf: resource not found on classpath: application.conf, application.json: resource not found on classpath: application.json, application.properties: resource not found on classpath: application.properties]
        at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:81)
        at play.api.Configuration$.load(Configuration.scala:58)
        at play.api.WithDefaultConfiguration$$anonfun$initialConfiguration$1.apply(Application.scala:74)
        at play.api.WithDefaultConfiguration$$anonfun$initialConfiguration$1.apply(Application.scala:74)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
        at play.api.WithDefaultConfiguration$class.initialConfiguration(Application.scala:73)
        at play.api.DefaultApplication.initialConfiguration$lzycompute(Application.scala:383)
        at play.api.DefaultApplication.initialConfiguration(Application.scala:383)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$globalClass(Application.scala:24)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalClass$lzycompute(Application.scala:383)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalClass(Application.scala:383)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:30)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal$lzycompute(Application.scala:383)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:383)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:52)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:51)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$globalInstance(Application.scala:50)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance$lzycompute(Application.scala:383)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance(Application.scala:383)
        at play.api.WithDefaultGlobal$class.global(Application.scala:66)
        at play.api.DefaultApplication.global(Application.scala:383)
        at play.api.WithDefaultConfiguration$class.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:80)
        at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration$lzycompute(Application.scala:383)
        at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:383)
        at play.api.WithDefaultConfiguration$class.configuration(Application.scala:82)
        at play.api.DefaultApplication.configuration(Application.scala:383)
        at play.api.Application$class.$init$(Application.scala:268)
        at play.api.DefaultApplication.<init>(Application.scala:383)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:52)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:230)
        at play.core.server.NettyServer$$anonfun$main$5.apply(NettyServer.scala:261)
        at play.core.server.NettyServer$$anonfun$main$5.apply(NettyServer.scala:260)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:260)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: com.typesafe.config.ConfigException$IO: application: application.conf: resource not found on classpath: application.conf, application.json: resource not found on classpath: application.json, application.properties: resource not found on classpath: application.properties
        at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:230)
        at com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:127)
        at com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:758)
        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:92)
        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:115)
        at com.typesafe.config.ConfigFactory.loadDefaultConfig(ConfigFactory.java:196)
        at com.typesafe.config.ConfigFactory.loadDefaultConfig(ConfigFactory.java:173)
        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:297)
        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:266)
        at play.api.Configuration$.dontAllowMissingConfig$lzycompute(Configuration.scala:25)
        at play.api.Configuration$.dontAllowMissingConfig(Configuration.scala:25)
        at play.api.Configuration$.load(Configuration.scala:60)
        ... 34 more
[root@xxx current]#

**Comment by yesnault** [comment]
Ton fichier restart.sh est-il strictement le même que : https://github.com/soapower/soapower/blob/master/restart.sh ?

**Comment by smoysan** [comment]
Oui c'est bien le cas.

**Comment by yesnault** [comment]
Il ne faut pas recopier le fichier start d'une installation précédente, mais bien garder celui qui est dans l'archive.

**Comment by smoysan** [comment]
Oui, j'ai effectivement copié le fichier start de la version précédente, mauvaise manip' de ma part.

Merci encore.
