### ISSUE TITLE
Search - Crash with large data

### ISSUE THREAD

**Issue by yesnault** [soapower/soapower#83]
```
play.api.Application$$anon$1: Execution exception[[DetailedDatabaseException: DatabaseException['Runner error: Overflow sort stage buffered data usage of 33556140 bytes exceeds internal limit of 33554432 bytes' (code = 17144)]]]
    at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.2]
    at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10.jar:2.2.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10.jar:2.2.2]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
    at scala.util.Try$.apply(Try.scala:161) [scala-library.jar:na]
    at scala.util.Failure.recover(Try.scala:185) [scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
    at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.2]
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
    at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
Caused by: reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['Runner error: Overflow sort stage buffered data usage of 33556140 bytes exceeds internal limit of 33554432 bytes' (code = 17144)]
    at reactivemongo.core.errors.ReactiveMongoException$.apply(errors.scala:32) ~[reactivemongo_2.10-0.10.0.jar:0.10.0]
    at reactivemongo.core.protocol.Response.error$lzycompute(protocol.scala:263) ~[reactivemongo_2.10-0.10.0.jar:0.10.0]
    at reactivemongo.core.protocol.Response.error(protocol.scala:258) ~[reactivemongo_2.10-0.10.0.jar:0.10.0]
    at reactivemongo.core.actors.MongoDBSystem$$anonfun$receive$1.applyOrElse(actors.scala:443) ~[reactivemongo_2.10-0.10.0.jar:0.10.0]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498) ~[akka-actor_2.10-2.2.1.jar:2.2.1]
    at akka.actor.ActorCell.invoke(ActorCell.scala:456) ~[akka-actor_2.10-2.2.1.jar:2.2.1]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237) ~[akka-actor_2.10-2.2.1.jar:2.2.1]
    at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[akka-actor_2.10-2.2.1.jar:2.2.1]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10-2.2.1.jar:2.2.1]
    ... 4 common frames omitted
```

Is it possible to make sort / filter on server (and not in javascript) ?

**Comment by guilefranc** [comment]
You mean sorting / filtering the list of requestData after the mongo query ?

**Comment by yesnault** [comment]
Paging before (If 100 elements / page -> 100 documents retrieve from MongoDB instead of all as today), and then, sorting / filtering if possible.

**Comment by guilefranc** [comment]
Ok it should be possible, i start working on it

**Comment by guilefranc** [comment]
We will still need a request on all the requestData in Mongo just to get the total number of requestData that match the filter in the search page.

**Comment by yesnault** [comment]
Yes, with aggregation framework will be great for that.

**Comment by guilefranc** [comment]
I have updated the Search so that it now only retrieve a small number of requestData first and then it retrieve a number of requestData based on requestData / page and number of page.

**Comment by yesnault** [comment]
It's fixed with : 
- only one request to server
- search in mongoDB with aggregation framework only (for search and compute total size)

Using aggregation framework avoid to read limitation of 32mo with sorting
